### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Akmal249** [AyraHikari/genshin_impact-daily#3]
This code is no longer work since last update v2.1

**Comment by AyraHikari** [comment]
Hello, can you tell the detail?
Because it still works in my current account

**Comment by Akmal249** [comment]
> Hello, can you tell the detail?
> Because it still works in my current account

For now i cant tell you the detail, maybe i will update my secret code first or repeat the intructions again and check the result tomorow.

**Comment by AyraHikari** [comment]
It's been 5 days i'll close this, if you still feel it did not work, please comment again.
Thanks
